-- USER SQL
CREATE USER serviexpress IDENTIFIED BY seba 
DEFAULT TABLESPACE ""
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER  serviexpress QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "CONNECT" TO  serviexpress;
GRANT "RESOURCE" TO serviexpress;
ALTER USER  serviexpress DEFAULT ROLE "CONNECT","RESOURCE";
GRANT CREATE VIEW TO  serviexpress;
