//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiExpress.LoginService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services/", ConfigurationName="LoginService.LoginService")]
    public interface LoginService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userName del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/LoginService/getRolRequest", ReplyAction="http://services/LoginService/getRolResponse")]
        ServiExpress.LoginService.getRolResponse getRol(ServiExpress.LoginService.getRolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/LoginService/getRolRequest", ReplyAction="http://services/LoginService/getRolResponse")]
        System.Threading.Tasks.Task<ServiExpress.LoginService.getRolResponse> getRolAsync(ServiExpress.LoginService.getRolRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nameUser del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services/LoginService/loginRequest", ReplyAction="http://services/LoginService/loginResponse")]
        ServiExpress.LoginService.loginResponse login(ServiExpress.LoginService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/LoginService/loginRequest", ReplyAction="http://services/LoginService/loginResponse")]
        System.Threading.Tasks.Task<ServiExpress.LoginService.loginResponse> loginAsync(ServiExpress.LoginService.loginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRol", Namespace="http://services/", Order=0)]
        public ServiExpress.LoginService.getRolRequestBody Body;
        
        public getRolRequest() {
        }
        
        public getRolRequest(ServiExpress.LoginService.getRolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getRolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public getRolRequestBody() {
        }
        
        public getRolRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRolResponse", Namespace="http://services/", Order=0)]
        public ServiExpress.LoginService.getRolResponseBody Body;
        
        public getRolResponse() {
        }
        
        public getRolResponse(ServiExpress.LoginService.getRolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getRolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getRolResponseBody() {
        }
        
        public getRolResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://services/", Order=0)]
        public ServiExpress.LoginService.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(ServiExpress.LoginService.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nameUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passUser;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string nameUser, string passUser) {
            this.nameUser = nameUser;
            this.passUser = passUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://services/", Order=0)]
        public ServiExpress.LoginService.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(ServiExpress.LoginService.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginServiceChannel : ServiExpress.LoginService.LoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<ServiExpress.LoginService.LoginService>, ServiExpress.LoginService.LoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.LoginService.getRolResponse ServiExpress.LoginService.LoginService.getRol(ServiExpress.LoginService.getRolRequest request) {
            return base.Channel.getRol(request);
        }
        
        public string getRol(string userName) {
            ServiExpress.LoginService.getRolRequest inValue = new ServiExpress.LoginService.getRolRequest();
            inValue.Body = new ServiExpress.LoginService.getRolRequestBody();
            inValue.Body.userName = userName;
            ServiExpress.LoginService.getRolResponse retVal = ((ServiExpress.LoginService.LoginService)(this)).getRol(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.LoginService.getRolResponse> ServiExpress.LoginService.LoginService.getRolAsync(ServiExpress.LoginService.getRolRequest request) {
            return base.Channel.getRolAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.LoginService.getRolResponse> getRolAsync(string userName) {
            ServiExpress.LoginService.getRolRequest inValue = new ServiExpress.LoginService.getRolRequest();
            inValue.Body = new ServiExpress.LoginService.getRolRequestBody();
            inValue.Body.userName = userName;
            return ((ServiExpress.LoginService.LoginService)(this)).getRolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiExpress.LoginService.loginResponse ServiExpress.LoginService.LoginService.login(ServiExpress.LoginService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public bool login(string nameUser, string passUser) {
            ServiExpress.LoginService.loginRequest inValue = new ServiExpress.LoginService.loginRequest();
            inValue.Body = new ServiExpress.LoginService.loginRequestBody();
            inValue.Body.nameUser = nameUser;
            inValue.Body.passUser = passUser;
            ServiExpress.LoginService.loginResponse retVal = ((ServiExpress.LoginService.LoginService)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiExpress.LoginService.loginResponse> ServiExpress.LoginService.LoginService.loginAsync(ServiExpress.LoginService.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiExpress.LoginService.loginResponse> loginAsync(string nameUser, string passUser) {
            ServiExpress.LoginService.loginRequest inValue = new ServiExpress.LoginService.loginRequest();
            inValue.Body = new ServiExpress.LoginService.loginRequestBody();
            inValue.Body.nameUser = nameUser;
            inValue.Body.passUser = passUser;
            return ((ServiExpress.LoginService.LoginService)(this)).loginAsync(inValue);
        }
    }
}
